# Generated by Django 5.0.12 on 2025-02-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images", verbose_name="Логотип"
            ),
        ),
    ]
