# Generated by Django 5.0.12 on 2025-02-28 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0002_alter_userprofile_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postphoto",
            name="child",
        ),
        migrations.CreateModel(
            name="ChildPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social_network.child",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social_network.postphoto",
                    ),
                ),
            ],
        ),
    ]
