# Generated by Django 5.0.12 on 2025-03-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0004_userprofile_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="child",
            name="last_name",
        ),
    ]
