# Generated by Django 5.0.12 on 2025-03-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0005_remove_child_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="gender",
            field=models.TextField(default=1, verbose_name="Пол"),
            preserve_default=False,
        ),
    ]
